
APPLICATION_ROOT = '/home/spenteco/1/onlineMalletV4/'

REPO_LOCATION = '/home/spenteco/0/malletData/onlineMalletDataRepo/'
STOPWORDS_REPO_FOLDER = 'stopwords/'
CORPUS_REPO_FOLDER = 'texts/'
RESULTS_REPO_LOCATION = 'results/'
LOG_REPO_LOCATION = 'logs/'

BATCH_SCRIPTS_LOCATION = APPLICATION_ROOT + 'onlineMalletV4/'

JOB_LOG_LOCATION = '/home/spenteco/0/malletData/onlineMalletDataRepo/logs/'

TEMP_LOCATION = '/home/spenteco/0/malletData/onlineMalletTemp/'

MALLET_BIN_FOLDER = '/home/spenteco/0/mallet-2.0.7/bin/'

BATCH_JOB_LIMIT = 2

SITE_PACKAGES = '/home/spenteco/1/onlineMalletV4/onlineMalletV4/env64/lib/python2.7/site-packages'
